config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'pages#home'

  resources :uploads

  resources :illustrations

  resources :blueprints

  resources :designs, except: :show do
    collection do
      get 'latest'
      get 'popular'
    end
  end

  get '/3d-model/:category/:id', to: 'designs#show', as: :design_show, constraints: { id: /.*\D+.*/ }
  get '/design/download/:id', to: 'designs#download', as: :design_download, constraints: { id: /.*\D+.*/ }
  match '/design/like/:id', to: 'designs#like', via: %i[post delete], as: :design_like, constraints: { id: /.*\D+.*/ }

  devise_for :users, path: '', controllers: { omniauth_callbacks: :omniauth_callbacks,
                                              registrations: :registrations,
                                              sessions: :sessions,
                                              confirmations: :confirmations,
                                              passwords: :passwords,
                                              unlocks: :unlocks }

  devise_scope :user do
    get '/auth/:provider/omniauth_error' => 'omniauth_callbacks#omniauth_error', as: :omniauth_error
  end

  get 'exists/:username', to: 'users#exists',
                          username: /(?:[a-zA-ZğüşıöçĞÜŞİÖÇ0-9_\.\%][a-zA-ZğüşıöçĞÜŞİÖÇ0-9_\-\.\%]*[a-zA-ZğüşıöçĞÜŞİÖÇ0-9_\-\%]|[a-zA-ZğüşıöçĞÜŞİÖÇ0-9_])/
  # TODO: Boyutluseyler::PathRegex

  resource :profile, only: %i[show update] do
    scope module: :profiles do
      resource :account, only: %i[show update] do
        member do
          delete :unlink
        end
      end
      resource :password, only: %i[edit update] do
        member do
          put :reset
        end
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  constraints(Boyutluseyler::AdminConstraint) do
    mount Sail::Engine => '/sail'
    mount Sidekiq::Web => '/sidekiq'
  end

  # this should be last route
  # TODO: redirect 404 page (customize 404 page)
  get '*path' => redirect('/')
end

app/models/design.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: designs
#
#  id                        :bigint(8)        not null, primary key
#  name                      :string(120)      not null
#  description               :text             not null
#  printing_settings         :text
#  model_file_format         :string
#  license_type              :string           not null
#  allow_comments            :boolean          default(TRUE), not null
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  user_id                   :bigint(8)        not null
#  category_id               :bigint(8)        not null
#  slug                      :string
#  downloads_count           :integer          default(0), not null
#  hourly_downloads_count    :float            default(0.0), not null
#  popularity_score          :float            default(0.0), not null
#  home_popular_at           :datetime
#  likes_count               :integer          default(0), not null
#  hourly_downloads_count_at :datetime
#  cached_tag_names          :text
#

class Design < ApplicationRecord
  extend FriendlyId

  include Taggable
  include Sortable

  friendly_id :name, use: %i[slugged history]
  resourcify

  HOURLY_DOWNLOAD_INTERVAL = 1.hour
  POPULAR_INTERVAL = 1.hour
  MOST_DOWNLOADED_LIMIT = 8
  POPULAR_LIMIT = 12
  POPULARITY_EFFECT = 0.02

  has_many :design_illustrations, -> { order(position: :asc) }, inverse_of: :design
  has_many :illustrations, through: :design_illustrations
  has_many :design_blueprints, -> { order(position: :asc) }, inverse_of: :design
  has_many :blueprints, through: :design_blueprints
  has_one :design_download, dependent: :destroy

  belongs_to :user
  belongs_to :category

  validates :name, presence: true, length: { maximum: 120 }
  validates :description, presence: true
  validates :license_type, presence: true
  validates :design_illustrations, presence: true
  validates :design_blueprints, presence: true

  scope :downloaded, -> { where('downloads_count > 0') }
  scope :eligible_for_hourly_download_calculation, (lambda do
    where('designs.created_at < ?', Time.current - HOURLY_DOWNLOAD_INTERVAL)
  end)

  enum license_type: {
    license_none: 'license_none',
    cc_by: 'cc_by',
    cc_by_sa: 'cc_by_sa',
    cc_by_nd: 'cc_by_nd',
    cc_by_nc: 'cc_by_nc',
    cc_by_nc_sa: 'cc_by_nc_sa',
    cc_by_nc_nd: 'cc_by_nc_nd'
  }

  def preview_blueprints
    blueprints.where(preview: true).select(:url, :thumb_url)
  end

  def preview_illustrations
    illustrations.select(:id, :thumb_url, 'large_url as url')
  end

  def cached_category_name
    Rails.cache.fetch(['Design', id, 'Category', category_id], expires_in: 1.month) do
      category.name
    end
  end

  def cached_user
    Rails.cache.fetch(['Design', id, 'User', user_id], expires_in: 1.month) do
      OpenStruct.new(username: user.username, avatar_url: user.avatar_url)
    end
  end

  class << self
    delegate :with_illustration, to: :most_downloaded, prefix: true
    delegate :with_illustration, to: :most_popular, prefix: true

    def sort_by_attribute(method)
      case method.to_s
      when 'downloads_count_desc' then reorder(downloads_count: :desc)
      when 'downloads_count_asc'  then reorder(downloads_count: :asc)
      when 'likes_count_desc'     then reorder(likes_count: :desc)
      when 'likes_count_asc'      then reorder(likes_count: :asc)
      when 'home_popular_at_desc' then reorder(home_popular_at: :desc)
      when 'home_popular_at_asc'  then reorder(home_popular_at: :asc)
      else order_by(method)
      end
    end

    def most_downloaded
      downloaded.eligible_for_hourly_download_calculation
                .order(hourly_downloads_count: :desc, created_at: :desc)
                .limit(MOST_DOWNLOADED_LIMIT)
    end

    def most_popular
      order(popularity_score: :desc).limit(POPULAR_LIMIT)
    end

    def popular
      where.not(home_popular_at: nil)
    end

    def with_illustration
      first_illustration.joins(:category).select('designs.id, designs.name, designs.slug,
        illustrations.medium_url, categories.slug as category_slug')
    end

    def cached_most_downloaded
      design_list = Rails.cache.fetch('most_downloaded',
                                      expires_in: HOURLY_DOWNLOAD_INTERVAL) do
        hourly_downloads_count_service.execute

        # TODO: use fast_jsonapi serializer
        most_downloaded_with_illustration.to_json(except: :tag_names)
      end

      JSON.parse(design_list)
    end

    def cached_popular_designs
      design_list = Rails.cache.fetch('popular_designs', expires_in: POPULAR_INTERVAL) do
        become_popular_service.execute

        # TODO: use fast_jsonapi serializer
        most_popular_with_illustration.to_json(except: :tag_names)
      end

      JSON.parse(design_list)
    end

    def invalidate_most_downloaded_cache
      Rails.cache.delete('most_downloaded')
    end

    def invalidate_popular_designs_cache
      Rails.cache.delete('popular_designs')
    end

    private

    def first_illustration
      joins(:illustrations).where('design_illustrations.position = ?', 1)
    end

    def hourly_downloads_count_service
      Designs::Downloads::HourlyDownloadsCountService.new
    end

    def become_popular_service
      Designs::BecomePopularService.new
    end
  end

  private

  # https://github.com/norman/friendly_id/blob/984dac788d106faf60313cd0e51593474a513078/lib/friendly_id/slugged.rb#L191
  def should_generate_new_friendly_id?
    name_changed? || super
  end
end

app/controllers/designs_controller.rb
# frozen_string_literal: true

class DesignsController < ApplicationController
  include AhoyActions

  before_action :authenticate_user!, except: %i[show latest popular]
  before_action :design, only: %i[show edit update destroy download like]

  def new
    authorize Design

    @design = Design.new
    @illustrations = {}
    @blueprints = {}
  end

  def show
    @illustrations = BuildSerializer.new(design.preview_illustrations,
                                         fields: { illustration: file_preview_fields })
                                    .serialize

    @blueprints = BuildSerializer.new(design.preview_blueprints,
                                      fields: { blueprint: file_preview_fields })
                                 .serialize

    @page_views_count = Ahoy::Event.where_event(Ahoy::Event::VIEWED_DESIGN,
                                                design_id: design.id).count

    Designs::PageViews::AfterPageViewService.new(design, current_user, controller: self).execute
  end

  def create
    authorize Design

    @design = Designs::CreateService.new(nil, current_user, design_params).execute

    if @design.persisted?
      redirect_to design_show_path(@design.category.slug, @design)
    else
      design_files_for(:create_error)

      render :new
    end
  end

  def edit
    design_files_for(:edit)
  end

  def update
    @design = Designs::UpdateService.new(design, current_user, design_params).execute

    if @design.valid?
      redirect_to action: :edit
    else
      design_files_for(:update_error)

      render :edit
    end
  end

  def destroy
    Designs::DestroyService.new(design, current_user).execute

    redirect_to root_path
  end

  def download
    url = Designs::Downloads::StateMachineService.new(design).execute

    Designs::Downloads::AfterDownloadService.new(design,
                                                 current_user,
                                                 controller: self).execute

    render json: { url: url }, status: :ok
  end

  def like
    Designs::Likes::AfterLikeService.new(design, current_user, controller: self).execute
  end

  def latest
    authorize Design

    @pagy, @designs = pagy(DesignsFinder.new(design_list_params).execute)
  end

  def popular
    authorize Design

    params[:popularity] = true
    @pagy, @designs = pagy(DesignsFinder.new(design_list_params).execute)
  end

  private

  def design_files_for(action)
    lists = Designs::Files::ListService.new(list_options_for(action)).execute

    @illustrations = BuildSerializer.new(lists[:illustrations],
                                         fields: { illustration: file_detail_fields })
                                    .serialize

    @blueprints = BuildSerializer.new(lists[:blueprints],
                                      fields: { blueprint: file_detail_fields })
                                 .serialize
  end

  def list_options_for(action)
    opts = {}

    opts[:action] = action
    case action
    when :create_error
      opts[:design] = @design
      opts[:params] = design_params
    when :update_error
      opts[:design] = design
      opts[:params] = design_params
    when :edit
      opts[:design] = design
    end

    opts
  end

  def design
    @design ||= Design.friendly.find(params[:id])
    authorize @design
  end

  def design_params
    params.require(:design).permit(design_params_attributes)
  end

  def design_params_attributes
    [
      :name,
      :description,
      :printing_settings,
      :license_type,
      :tags_as_string,
      :allow_comments,
      :category_id,
      illustration_ids: [],
      blueprint_ids: []
    ]
  end

  def design_list_params
    params[:with_illustration] = true
    params.permit(%i[direction sort page with_illustration popularity])
  end

  def file_preview_fields
    %i[id url thumbUrl]
  end

  def file_detail_fields
    %i[id url thumbUrl filename size]
  end
end

app/helpers/designs_helper.rb
# frozen_string_literal: true

module DesignsHelper
  def license_title_for(design)
    # TODO: i18n
    return 'Telif Hakkı' if design.license_type == 'license_none'

    'Lisans'
  end
end

app/views/designs/_box.html.haml
%article.designs.box
  %a.box-thumb{ title: design['name'], href: design_show_path(design['category_slug'], design['slug']) }
    %img{ src: design['medium_url'], width: 234, height: 234 }

app/views/designs/_form.html.haml
- content_for :head do
  = javascript_pack_tag 'user/designs'
.container.mt-4.mb-4
  = simple_form_for(@design, validate: true) do |f|
    = render 'layouts/errors_inline', object: @design
    = render 'layouts/flash'
    .twins.row.grid-divider
      .twin.col-md-6
        = f.input :name, required: true, validate: true

        = f.input :description, required: true, input_html: { rows: 8 }

        = f.input :printing_settings, input_html: { rows: 5 }

        = f.association :category, collection: Category.cached_categories.map { |c| [c['name'], c['id']] }, required: true

        = f.input :tags_as_string

        = f.input :license_type, required: true,
          collection: human_enum_collection(Design, :license_types),
          selected: f.object.license_type || 'license_none'

        .form-group.d-flex
          %label.custom-toggle
            = f.input_field :allow_comments, as: :boolean, id: 'cb_allow_comments', boolean_style: :inline, required: true
            %span.custom-toggle-slider.rounded-circle
          %label.ml-2{ for: 'cb_allow_comments' }= t('simple_form.labels.design.allow_comments')

      .twin.col-md-6
        - direct_upload_allowed = policy(:direct_upload).new?
        %label.form-control-label Dosyalar
        - if direct_upload_allowed
          .js-connected-uploader{ data: { behavior: 'vue' } }
            %connected-uploader{ accept: '.stl,.obj,.ply,.zip,.STL,.OBJ,.ZIP',
              'add-button-text' => 'STL, OBJ, PLY, ZIP dosyaları ekleyin veya sürükleyin…',
              'remove-button-text' => 'Kaldır',
              'direct-url' => Boyutluseyler.config[:direct_upload_endpoint],
              'uploader-url' => '/uploads/new?policy_name=blueprint',
              'create-url' => '/blueprints',
              'input-name' => 'design[blueprint_ids][]',
              'data-type' => 'blueprint',
              ':files' => @blueprints }
        - else
          %p.description.font-weight-400.mt-3= t('pundit.errors.design.direct_upload')

        %label.form-control-label.mt-3 Fotoğraflar
        - if direct_upload_allowed
          .js-connected-uploader{ data: { behavior: 'vue' } }
            %connected-uploader{ accept: '.jpg,.jpeg,.gif,.png,.JPG,.JPEG,.GIF,.PNG',
              'add-button-text' => 'JPG, GIF veya PNG dosyaları ekleyin veya sürükleyin…',
              'remove-button-text' => 'Kaldır',
              'direct-url' => Boyutluseyler.config[:direct_upload_endpoint],
              'uploader-url' => '/uploads/new?policy_name=illustration',
              'create-url' => '/illustrations',
              'input-name' => 'design[illustration_ids][]',
              'data-type' => 'illustration',
              ':files' => @illustrations }
        - else
          %p.description.font-weight-400.mt-3= t('pundit.errors.design.direct_upload')

        %p.description.font-weight-400.mt-3 Dosyalar üzerinde sürükle bırak yaparak sıralamayı belirleyebilirsiniz..
        %p.description.opacity-8.font-weight-400 Fotoğraflar için ilk sıradaki resim tasarımınızı temsil eder.
        %p.description.opacity-8.font-weight-400 Dikkat çekici resimlerinizi üst sıralara koyarak görüntülenme şansını arttırabilirsiniz.

        = f.button :submit, 'Gönder', class: 'btn btn-primary'

app/views/designs/_most_downloaded.html.haml
%section#most-downloaded.explore-section
  %h6.font-roboto.font-weight-700.mb-0 En Çok İndirilenler
  - if @most_downloaded.any?
    .designs-group
      - @most_downloaded.each do |d|
        = render partial: 'designs/box', locals: { design: d }
    .explore-section-more
      %a{ title: 'En Çok İndirilenler', href: '/designs/latest?direction=desc&sort=downloads_count' } Daha fazla
  - else
    .rich.content
      %p.text-sm Henüz indirilen bir tasarım yok

app/views/designs/_nav_sort.html.haml
- d_desc = ApplicationHelper::D_DESC
- sort_by_date = "#{url_path}?#{d_desc}&sort=#{date}"
- sort_by_download = "#{url_path}?#{d_desc}&sort=#{downloads}"
- sort_by_like = "#{url_path}?#{d_desc}&sort=#{likes}"

%nav.sort.font-roboto
  .sort-text Sırala:
  - active = active_class_for(date)
  - link = toggle_sort_link(sort_by_date, active)
  = render partial: 'designs/nav_sort_link', locals: { active: active, text: 'Tarih', link: link }

  - active = active_class_for(downloads)
  - link = toggle_sort_link(sort_by_download, active)
  = render partial: 'designs/nav_sort_link', locals: { active: active, text: 'İndirme', link: link }

  - active = active_class_for(likes)
  - link = toggle_sort_link(sort_by_like, active)
  = render partial: 'designs/nav_sort_link', locals: { active: active, text: 'Beğeni', link: link }

app/views/designs/_nav_sort_link.html.haml
%a.sort-item{ class: active ? 'sort-active' : '', href: link }
  - if active
    - if link.include?(ApplicationHelper::D_ASC)
      %span.btn-inner--icon
        %span= "#{text} "
        %span.sort-icon ∨
    - else
      %span.btn-inner--icon
        %span= "#{text} "
        %span.sort-icon ∧
  - else
    %span= text

app/views/designs/_popular.html.haml
%section#popular-designs.explore-section.mt-5
  %h6.font-roboto.font-weight-700.mb-0 Popüler Tasarımlar
  - if @popular_designs.any?
    .designs-group
      - @popular_designs.each do |d|
        = render partial: 'designs/box', locals: { design: d }
    .explore-section-more
      %a{ title: 'Popüler Tasarımlar', href: '/designs/popular?direction=desc&sort=home_popular_at' } Daha fazla
  - else
    .rich.content
      %p.text-sm Henüz popüler olan bir tasarım yok

app/views/designs/edit.html.haml
.container-fluid.bg-secondary
  .container
    .d-flex.mt-4
      %div
        -# TODO: i18n
        %span.badge.badge-primary.badge-pill Tasarımı Düzenle
        -# TODO: i18n
      .ml-auto
        %a.btn-xs.btn-outline-default.border-solid.no-outline{ href: design_show_path(@design.category.slug, @design) } Görüntüle
    %h5.display-4.card-title.mt-3 #{@design.name}
= render 'form'

app/views/designs/latest.html.haml
- content_for :head do
  = javascript_pack_tag 'designs/latest'

- url_path = '/designs/latest'
- date = 'created'
- downloads = 'downloads_count'
- likes = 'likes_count'

%main
  %section.section.section-xs
    .container
      .grid.grid--full--large
        .grid-cell
          %h6.mt-3.font-roboto.font-weight-500.mb-0 En Yeni 3D Modeller
        .grid-cell.grid-cell--fit
          = render partial: 'designs/nav_sort', locals: { url_path: url_path, date: date, downloads: downloads, likes: likes }
      - if @designs.any?
        .designs-group.mb-3
          - @designs.each do |d|
            = render partial: 'designs/box', locals: { design: d }
        %nav{ 'aria-label' => 'pagination' }
          %ul.pagination.justify-content-center
            = pagy_bootstrap_nav_js(@pagy).html_safe
      - else
        .rich.content
          %p.text-sm Henüz bir tasarım yok

app/views/designs/new.html.haml
.container-fluid.section-title.bg-secondary
  .container
    -# TODO: i18n
    %span.badge.badge-primary.badge-pill.mt-4 Yeni Tasarım
= render 'form'

app/views/designs/popular.html.haml
- content_for :head do
  = javascript_pack_tag 'designs/popular'

- url_path = '/designs/popular'
- date = 'home_popular_at'
- downloads = 'downloads_count'
- likes = 'likes_count'

%main
  %section.section.section-xs
    .container
      .grid.grid--full--large
        .grid-cell
          %h6.mt-3.font-roboto.font-weight-500.mb-0 En Çok Sevilen 3D Modeller
        .grid-cell.grid-cell--fit
          = render partial: 'designs/nav_sort', locals: { url_path: url_path, date: date, downloads: downloads, likes: likes }
      - if @designs.any?
        .designs-group.mb-3
          - @designs.each do |d|
            = render partial: 'designs/box', locals: { design: d }
        %nav{ 'aria-label' => 'pagination' }
          %ul.pagination.justify-content-center
            = pagy_bootstrap_nav_js(@pagy).html_safe
      - else
        .rich.content
          %p.text-sm Henüz popüler olan bir tasarım yok

app/views/designs/show.html.haml
- content_for :head do
  = javascript_pack_tag 'design'
-# TODO: i18n all page
.container
  .d-flex.mt-4
    %div
      %h3.text-primary.font-weight-600= @design.name
    - edit_design_allowed = policy(@design).edit?
    - delete_design_allowed = policy(@design).destroy?
    - if edit_design_allowed || delete_design_allowed
      .ml-auto.mt-2
        .d-flex
          - if edit_design_allowed
            = link_to t('helpers.button.edit'), edit_design_path, class: 'btn-xs btn-outline-default border-solid no-outline'
          - if delete_design_allowed
            -# TODO: soft delete by request via form + slack integration
            = link_to t('helpers.button.delete'), design_path(@design), method: :delete, data: { confirm: 'Emin misin?' }, class: 'btn-xs btn-outline-default border-solid no-outline ml-1'

  .design
    .design-photos
      .actionbar
        .js-content-preview-toggle-button.actionbar-left{ data: { behavior: 'vue' } }
          %content-preview-toggle-button{ 'css-class': 'btn-xs btn-outline-primary no-outline' }
        .js-like-button.actionbar-right{ data: { behavior: 'vue' } }
          %like-button{ 'like-css-class': 'btn-xs btn-primary no-outline border-solid btn-icon', 'unlike-css-class': 'btn-xs btn-gray no-outline border-solid btn-icon', 'like-text': 'BEĞEN', 'unlike-text': 'BEĞENDİN', ':liked-status': liked_design?(@design.id), 'endpoint': design_like_path(@design) }
      .js-content-preview{ data: { behavior: 'vue' } }
        %content-preview{ 'data-type': 'illustration', 'content-type': 'image',
          ':files': @illustrations, 'toggle-button-text': 'Fotoğraflar',
          'default-thumb-url': image_path('B4B4B4-1.png'), ':active': true,
          'viewer-css-class': 'thumb', 'img-alt-tag': 'Ücretsiz 3D baskı dosyaları' }
        %content-preview{ 'data-type': 'blueprint', 'content-type': 'model',
          ':file-extensions': %w[stl obj], ':files': @blueprints,
          'toggle-button-text': '3D Görünüm', 'default-thumb-url': image_path('3d.svg'),
          'img-bg-color': '#fff', 'viewer-css-class': 'model',
          'img-alt-tag': 'Ücretsiz 3D baskı dosyaları' }
    .design-infos
      .d-flex.mb-3
        .ml-auto
          .js-download-button{ data: { behavior: 'vue' } }
            %download-button{ 'css-class': 'btn-xs btn-primary no-outline border-solid border-width-15x btn-icon', 'text': t('helpers.button.download'),
            'downloading-text': t('helpers.button.downloading'),
            'record-id': @design.id, 'endpoint': design_download_path(@design) }
      .d-flex.mb-2
        .ml-auto
          .js-page-counters{ data: { behavior: 'vue' } }
            %page-counters.page-counters{ ':views': { count: @page_views_count,  min: 0, textPlural: 'Toplam Görüntülenme', textSingular: 'Toplam Görüntülenme' }.to_json, ':downloads': { count: @design.downloads_count, min: 1, textPlural: 'İndirme', textSingular: 'İndirme' }.to_json, ':likes': { count: @design.likes_count, min: 1, textPlural: 'Beğeni', textSingular: 'Beğeni' }.to_json, locale: I18n.locale }
      %h6.d-inline.text-primary.mt-3 Kategori:
      .d-inline.opacity-8= @design.cached_category_name
      %h6.text-primary.mt-3 3D Model Açıklama
      .rich.content= simple_format(@design.description)
      %h6.text-primary.mt-3 3D Baskı Ayarları
      .rich.content= simple_format(@design.printing_settings)
      %h6.d-inline.text-primary.mt-3 3D Model Formatı:
      .d-inline.opacity-8= @design.model_file_format
      %h6.text-primary.mt-3 Etiketler
      %ul.inline-list
        - @design.cached_tag_name_list.each do |t|
          %li
            %a{ class: 'badge badge-pill badge-primary', href: "/tags/#{t}" }= t

      .license.float-right.mt-3
        %h6.text-primary= license_title_for(@design)
        = render partial: 'designs/shared/license', locals: { license_type: @design.license_type }