config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'pages#home'

  resources :uploads

  resources :illustrations

  resources :blueprints

  resources :designs, except: :show do
    collection do
      get 'latest'
      get 'popular'
    end
  end

  get '/3d-model/:category/:id', to: 'designs#show', as: :design_show, constraints: { id: /.*\D+.*/ }
  get '/design/download/:id', to: 'designs#download', as: :design_download, constraints: { id: /.*\D+.*/ }
  match '/design/like/:id', to: 'designs#like', via: %i[post delete], as: :design_like, constraints: { id: /.*\D+.*/ }

  devise_for :users, path: '', controllers: { omniauth_callbacks: :omniauth_callbacks,
                                              registrations: :registrations,
                                              sessions: :sessions,
                                              confirmations: :confirmations,
                                              passwords: :passwords,
                                              unlocks: :unlocks }

  devise_scope :user do
    get '/auth/:provider/omniauth_error' => 'omniauth_callbacks#omniauth_error', as: :omniauth_error
  end

  get 'exists/:username', to: 'users#exists',
                          username: /(?:[a-zA-ZğüşıöçĞÜŞİÖÇ0-9_\.\%][a-zA-ZğüşıöçĞÜŞİÖÇ0-9_\-\.\%]*[a-zA-ZğüşıöçĞÜŞİÖÇ0-9_\-\%]|[a-zA-ZğüşıöçĞÜŞİÖÇ0-9_])/
  # TODO: Boyutluseyler::PathRegex

  resource :profile, only: %i[show update] do
    scope module: :profiles do
      resource :account, only: %i[show update] do
        member do
          delete :unlink
        end
      end
      resource :password, only: %i[edit update] do
        member do
          put :reset
        end
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  constraints(Boyutluseyler::AdminConstraint) do
    mount Sail::Engine => '/sail'
    mount Sidekiq::Web => '/sidekiq'
  end

  # this should be last route
  # TODO: redirect 404 page (customize 404 page)
  get '*path' => redirect('/')
end

app/controllers/profiles/accounts_controller.rb
# frozen_string_literal: true

class Profiles::AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, except: %i[unlink]

  def show; end

  def unlink
    provider = params[:provider]
    identity = current_user.identities.find_by(provider: provider)

    return render_404 unless identity

    authorize :identity_provider, :unlink?

    identity.destroy

    redirect_to profile_account_path
  end

  private

  def set_user
    @user = current_user
    authorize @user
  end
end

app/controllers/profiles/passwords_controller.rb
# frozen_string_literal: true

class Profiles::PasswordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def edit; end

  def update
    password_attributes = user_params.select do |key, _value|
      %w[password password_confirmation].include?(key.to_s)
    end

    unless @user.valid_password?(user_params[:current_password])
      redirect_to edit_profile_password_path,
                  alert: t('activerecord.errors.models.user.attributes.current_password.invalid')
      return
    end

    result = Users::UpdateService.new(current_user, password_attributes.merge(user: @user)).execute

    if result[:status] == :success
      flash[:notice] = t('devise.registrations.password_updated_but_not_signed_in')
      redirect_to new_user_session_path
    else
      render 'edit'
    end
  end

  def reset
    current_user.send_reset_password_instructions
    redirect_to edit_profile_password_path,
                notice: t('devise.passwords.sent_reset_password_instructions')
  end

  private

  def set_user
    @user = current_user
    authorize @user
  end

  def user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :user

  def show; end

  def update
    respond_to do |format|
      result = Users::UpdateService.new(current_user, user_params.merge(user: @user)).execute

      if result[:status] == :success
        message = t('devise.registrations.updated')

        format.html { redirect_back_or_default(default: { action: 'show' }, options: { notice: message }) }
        format.json { render json: { message: message } }
      else
        format.html { redirect_back_or_default(default: { action: 'show' }, options: { alert: result[:message] }) }
        format.json { render json: result }
      end
    end
  end

  private

  def user
    @user = current_user
    authorize @user
  end

  def user_params
    @user_params ||= params.require(:user).permit(
      :email,
      :username,
      :avatar_url
    )
  end
end

app/views/profiles/accounts/_providers.html.haml
.row
  - providers.each do |provider|
    - image_tag = provider_image_tag(provider)
    - label_provider = label_for_provider(provider)
    - unlink_allowed = policy(:identity_provider).unlink?
    - link_allowed = policy(:identity_provider).link?
    - if unlink_allowed || link_allowed
      - if auth_active?(provider)
        .col-lg-6.col-md-12.mb-3
          - if unlink_allowed
            = link_to unlink_profile_account_path(provider: provider), method: :delete, class: 'btn btn-block btn-secondary btn-icon' do
              %span.btn-inner--icon
                = image_tag
              %span.btn-inner--text
                = "#{label_provider} Hesabını Çıkar"
          - else
            %a.btn.btn-block.btn-secondary.btn-icon
              %span.btn-inner--icon
                = image_tag
              %span.btn-inner--text
                = "#{label_provider} Hesabı Bağlı"
      - elsif link_allowed
        .col-lg-6.col-md-12.mb-3
          = link_to omniauth_authorize_path(:user, provider), method: :post, class: 'btn btn-block btn-secondary btn-icon' do
            %span.btn-inner--icon
              = image_tag
            %span.btn-inner--text
              = "#{label_provider} ile Bağlan"

app/views/profiles/accounts/show.html.haml
= render 'profiles/layout' do
  .card-2.mt-4
    .card-header-2.bg-white
      .row.align-items-center
        .col-8
          %h5.text-10625.font-weight-bold.mb-0 Hesap
    .card-body.pt-2
      - if display_providers_on_profile?
        %h6.heading-small.text-muted.mb-4 Bağlı Hesaplar
        = render 'providers', providers: auth_providers

// TODO: cancel account
-# %h4.mt-4= t('.cancel_my_account')
-# .d-flex.py-1
-# = button_to t('.cancel_my_account'), registration_path(resource_name),
-# method: :delete, class: 'btn btn-danger', data: { confirm: t('.are_you_sure') },
-# id: 'btn_cancel_my_account'