config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'pages#home'

  resources :uploads

  resources :illustrations

  resources :blueprints

  resources :designs, except: :show do
    collection do
      get 'latest'
      get 'popular'
    end
  end

  get '/3d-model/:category/:id', to: 'designs#show', as: :design_show, constraints: { id: /.*\D+.*/ }
  get '/design/download/:id', to: 'designs#download', as: :design_download, constraints: { id: /.*\D+.*/ }
  match '/design/like/:id', to: 'designs#like', via: %i[post delete], as: :design_like, constraints: { id: /.*\D+.*/ }

  devise_for :users, path: '', controllers: { omniauth_callbacks: :omniauth_callbacks,
                                              registrations: :registrations,
                                              sessions: :sessions,
                                              confirmations: :confirmations,
                                              passwords: :passwords,
                                              unlocks: :unlocks }

  devise_scope :user do
    get '/auth/:provider/omniauth_error' => 'omniauth_callbacks#omniauth_error', as: :omniauth_error
  end

  get 'exists/:username', to: 'users#exists',
                          username: /(?:[a-zA-ZğüşıöçĞÜŞİÖÇ0-9_\.\%][a-zA-ZğüşıöçĞÜŞİÖÇ0-9_\-\.\%]*[a-zA-ZğüşıöçĞÜŞİÖÇ0-9_\-\%]|[a-zA-ZğüşıöçĞÜŞİÖÇ0-9_])/
  # TODO: Boyutluseyler::PathRegex

  resource :profile, only: %i[show update] do
    scope module: :profiles do
      resource :account, only: %i[show update] do
        member do
          delete :unlink
        end
      end
      resource :password, only: %i[edit update] do
        member do
          put :reset
        end
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  constraints(Boyutluseyler::AdminConstraint) do
    mount Sail::Engine => '/sail'
    mount Sidekiq::Web => '/sidekiq'
  end

  # this should be last route
  # TODO: redirect 404 page (customize 404 page)
  get '*path' => redirect('/')
end

app/views/layouts/header/_default.html.haml
-# header element starts/
%header.header-global
  -# nav element starts/
  %nav#navbar-main.navbar.navbar-main.navbar-dark.bg-primary.navbar-colored.navbar-expand-lg
    .container
      %ul.navbar-nav.navbar-fixed.align-items-center
        %button.navbar-toggler{"aria-controls" => "navbar-global", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbar-global", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        = link_to root_path, class: 'navbar-brand' do
          = image_tag('icon.png')
          %span boyutluşeyler
      #navbar-global.navbar-collapse.collapse
        .navbar-collapse-header
          .row
            .col-6.collapse-brand
              %a{:href => "#"}
                = link_to root_path, class: 'navbar-brand-collapse' do
                  = image_tag('icon.png')
                  %span boyutluşeyler
            .col-6.collapse-close
              %button.navbar-toggler{"aria-controls" => "navbar-global", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbar-global", "data-toggle" => "collapse", :type => "button"}
                %span
                %span
        %ul.navbar-nav.align-items-lg-center
          - if header_link?(:library)
            %li.nav-item
              %a.nav-link{:href => "#"}
                %span.nav-link-inner--text Kütüphane
          - if header_link?(:explore)
            %li.nav-item.dropdown
              %a.nav-link{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                %span.nav-link-inner--text Keşfet
              .dropdown-menu.dropdown-menu-sm.dropdown-menu-left
                -# TODO: i18n
                = link_to '3D Model', root_path, class: 'dropdown-item'
                = link_to '3D Baskı', root_path, class: 'dropdown-item'
          - if header_link?(:category)
            %li.nav-item.dropdown
              %a.nav-link{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                %span.nav-link-inner--text Kategori
              .dropdown-menu.dropdown-menu-left
                - Category.cached_categories.each do |c|
                  = link_to c['name'], "/categories/#{c['slug']}", class: 'dropdown-item'
          - if header_link?(:upload)
            %li.nav-item
              %a.nav-link{:href => "/designs/new"}
                %span.nav-link-inner--text Yükle
      %ul.navbar-nav.navbar-fixed.align-items-center.ml-xs-auto
        - if header_link?(:search)
          %li.nav-item.mr-2
            %form.form-inline.my-2.my-lg-0
              .input-group
                .input-group-prepend
                  %span.input-group-text.search
                    %i.search-icon.fas.fa-search
                %input.form-control.search{"aria-label" => "Search", :placeholder => "Ara", :type => "search"}/
        - if header_link?(:sign_in)
          %li.nav-item.ml-2.mr-0
            = link_to t('devise.registrations.new.sign_up'), new_user_registration_path, class: 'nav-link nav-link-fixed', id: 'nav_sign_up'
          %li.nav-item.text-nowrap.mr-0
            = link_to t('devise.sessions.new.sign_in'), new_user_session_path, class: 'nav-link nav-link-fixed'
        - if header_link?(:user_dropdown)
          %li.nav-item.mr-2.ml-1.mt-1.dropdown
            %a#user-dropdown.nav-link-icon{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              %span.avatar.avatar-sm.rounded-circle
                %img{ alt: current_user.username, src: current_user.avatar_thumb_url }
            .dropdown-menu.dropdown-menu-sm.dropdown-menu-right{"aria-labelledby" => "user-dropdown"}
              -# TODO: i18n
              %a.dropdown-item{ href: '#' } Profil
              = link_to 'Ayarlar', profile_path, class: 'dropdown-item'
              = link_to t('devise.sessions.destroy.log_out'), destroy_user_session_path, method: :delete, class: 'dropdown-item'
  -# nav element ends
-# header element ends